sudo: false

language: go

go:
    - 1.5.3
    - tip

services:
    - docker

addons:
    apt:
        packages:
        - mysql-client-core-5.6
        - mysql-client-5.6

before_install:
    - cat /etc/hosts
    - docker pull mysql/mysql-server:5.6.29
    - docker run --name mysql_1 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -p 3301:3306 -d mysql/mysql-server:5.6.29 --log-bin=binlog --read-only=1
    - docker run --name mysql_2 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -p 3302:3306 -d mysql/mysql-server:5.6.29 --log-bin=binlog --read-only=1
    - docker run --name mysql_3 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -p 3303:3306 -d mysql/mysql-server:5.6.29 --log-bin=binlog --read-only=1
    - sleep 15
    - docker ps -a


install:
    - mysql -uroot -h127.0.0.1 -P3301 < prepare.sql
    - mysql -uroot -h127.0.0.1 -P3302 < prepare.sql
    - mysql -uroot -h127.0.0.1 -P3303 < prepare.sql
    - go get github.com/go-sql-driver/mysql

script:
    - go test ./...
